stages:
  - run-test
  - upload-report

#-----------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------
.qa_rules: &qa_rules
  - if: $QA_TEST == "true"

#-----------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------
.run-test:
  stage: run-test
  image:
    name: mcr.microsoft.com/playwright:v1.50.1-noble
    entrypoint: [""]
    pull_policy: [if-not-present, always]
  variables:
    CI: true
  script:
    - cd playwright
    - yarn install
    - yarn test
  cache:
    - key: "$CI_COMMIT_REF_NAME"
      paths:
        - playwright/node_modules

#-----------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------
run-test:dev:
  extends: .run-test
  rules:
    - *qa_rules
  artifacts:
    expire_in: 1 week
    name: "sanity-test-$CI_COMMIT_REF_NAME"
    paths:
      - playwright/playwright-report
